Disassembler cli
koute/polkavm pull request #44
Opened 2023-09-01 09:18 UTC by f-gate

Hi there, cool project. 
Thought id give this a go as its easy enough for my first open source contribution.

Solves: https://github.com/koute/polkavm/issues/34

2023-09-01 12:16 UTC, koute requested changes
Thanks for the PR!

Also, a question: did you run `rustfmt`? If not please run `cargo fmt --all`. (Sorry, I haven't yet set up the CI so this is not yet automatically verified.)

2023-09-01 18:21 UTC, f-gate commented on crates/polkavm/src/disassembler.rs
> +}
I attempted to use `module.instructions()` however, the visibility is only pub(crate). I thought this would be less invasive than  changing the visibility of the `module.instructions()` :).
```
 pub(crate) fn instructions(&self) -> &[RawInstruction] {
        &self.0.instructions
    }
```
Unless there is something im missing here.

2023-09-03 05:28 UTC, koute commented on crates/polkavm/src/disassembler.rs
> +}
You don't need to go through a `Module`. You can just parse the blob into a `ProgramBlob` and then call [`.instructions`](https://docs.rs/polkavm-common/0.1.1/polkavm_common/program/struct.ProgramBlob.html#method.instructions) on it, which is public.

2023-09-04 05:24 UTC, koute requested changes

2023-09-04 05:24 UTC, koute commented on tools/polkatool/src/main.rs
> +    /// Disassembles a .polkavmm blob into its human-readable assembly.
```suggestion
    /// Disassembles a .polkavm blob into its human-readable assembly.
```

Typo.

2023-09-04 05:24 UTC, koute commented on tools/polkatool/src/main.rs
> +        output: PathBuf,
```suggestion
        output: Option<PathBuf>,
```

Wasn't made optional. (:

2023-09-04 05:24 UTC, koute commented on tools/polkatool/src/main.rs
> +                .join("\n");
Open the file normally and turn this into a loop, instead of turning everyone into strings first.

For example, something like this:

```
let fp = match File::open(path) { .. };
let mut fp = BufWriter::new(fp);
for (nth_instruction, instruction) in blob.instructions.enumerate() {
    let instruction = match instruction { .. };
    writeln!(&mut fp, ..).unwrap();
}

match fp.flush() { .. }
```

2023-09-04 10:58 UTC, f-gate commented on tools/polkatool/src/main.rs
> +        output: PathBuf,
oops haha

2023-09-04 10:59 UTC, f-gate commented on tools/polkatool/src/main.rs
> +                .join("\n");
Awesome! thanks for this, much cleaner and simpler.

2023-09-05 05:46 UTC, koute requested changes

2023-09-05 05:46 UTC, koute commented on tools/polkatool/Cargo.toml
> +polkavm = { workspace = true }
```suggestion
```

You forgot to remove this. (:

2023-09-05 05:46 UTC, koute commented on tools/polkatool/src/main.rs
> +            let mut bw: Box<dyn Write> = match output {
This doesn't need to be boxed.

The easiest way to deal with it is to just move the body which does the dissasembly into a separate function, e.g. something like this:

```rust
fn disassemble_into(blob: &ProgramBlob, out: &mut dyn Write) {
    // ...
}

// ...
if let Some(path) = output {
    let mut fp = ...;
    disassemble_into(&blob, &mut fp);
} else {
    let mut fp = BufWriter::new(std::io::stdout());
    disassemble_into(&blob, &mut fp);
}
```

2023-09-05 05:46 UTC, koute commented on tools/polkatool/src/main.rs
> +                }
Just use `writeln!` directly instead of doing a `format!` first. (:

Also you can put the variables inline into the string itself.

This works:

```rust
writeln!(&mut fp, "{nth_instruction}: {instruction}")
```

2023-09-05 05:46 UTC, koute commented on tools/polkatool/src/main.rs
> +            bw.flush().unwrap();
This can fail with a write error, so don't `unwrap` it.

2023-09-07 12:05 UTC, koute requested changes

2023-09-07 12:05 UTC, koute commented on tools/polkatool/src/main.rs
> +        eprintln!("ERROR: failed to flush buffer writer. {}.", error);
```suggestion
        eprintln!("ERROR: failed to write to output: {}", error);
```

2023-09-07 12:05 UTC, koute commented on tools/polkatool/src/main.rs
> +                    error, nth_instruction
```suggestion
                    "ERROR: failed to parse instruction #{}: {}", nth_instruction, error
```

2023-09-07 12:05 UTC, koute commented on tools/polkatool/src/main.rs
> +                    eprintln!("ERROR: failed to write instruction from buffer. {:?} {}.", error, instruction);
```suggestion
                    eprintln!("ERROR: failed to write to output: {}", error);
```

2023-09-07 12:05 UTC, koute commented on tools/polkatool/src/main.rs
> +                    eprintln!("ERROR: failed to parse the raw data into a blob {:?}: {}", input, error);
```suggestion
                    eprintln!("ERROR: failed to parse {:?}: {}", input, error);
```

2023-09-07 12:05 UTC, koute commented on tools/polkatool/Cargo.toml
> +polkavm-linker = { workspace = true }
Could you please restore this newline? (: (Sorry!)

2023-09-07 12:07 UTC, koute commented
Almost good to go!

2023-09-07 12:39 UTC, f-gate commented
thanks for the awesome review, if it wasnt too much hassle for you ill try picking up some other pieces.

2023-09-07 14:45 UTC, koute commented on tools/polkatool/Cargo.toml
> +polkavm-linker = { workspace = true }
I meant the newline at the very end of the file, not *before* this line. (:

But it's fine; looks like I was able to fix it myself.

2023-09-07 14:46 UTC, koute commented
Okay, can you fix clippy and rustfmt?

2023-09-09 09:54 UTC, merged

2023-09-09 09:55 UTC, koute commented
Thanks!

> if it wasnt too much hassle for you ill try picking up some other pieces

That's fine, but please do consult with me before you pick anything substantial. Things are still very much in flux so not everything is appropriate for people to pick. (: